from .prog1 import display1
from .prog2 import display2
from .prog3 import display3
from .prog4 import display4
from .prog5 import display5
from .prog6 import display6
from .prog7 import display7
from .prog8 import display8
from .prog9 import display9
from .prog10 import display10
